# Generated by Django 4.1.5 on 2023-01-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='date_created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='date_updated_at',
        ),
    ]
