# Generated by Django 4.1.5 on 2023-01-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_created_at_user_date_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('USER', 'USER'), ('GERANT', 'GERANT'), ('ADMIN', 'ADMIN'), ('SUPERADMIN', 'SUPERADMIN')], default='USER', max_length=25),
        ),
    ]
