# Generated by Django 4.1.5 on 2023-01-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshop', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=12),
        ),
    ]
